os: linux
dist: focal
language: python
python: '3.8'

if: (branch = main OR tag IS present) AND (type = push)

env:
  global:
  - GEOS_VERSION=3.11.0
  - secure: Rg+fFrK8N8+jYqno6mfa/MfeUDV9mnUdJtsC02A6A1Umdcs3gwyyEfeEdDlJvJ94Sr04jwN/9WkTj5i7EyW6/ESq1mFaaSLqL456nyriJBHn7o/dJgKavl6E0EyXMbpfLXR4V+5cHfI/48PuX4BuDwlEZa+dLTjpDbvXIwb98sY=
  - secure: bJ5kz6dk3E9bYoBe//XF5d0xP1ksbc/uGVhZVgB6jRGYpkO/lpU7rIltiG//8LMH+heKK2vEUAo6lLGBPN3FMBx7Ti/UBlbQhw4NKdTW52Tzb8XY15MwcYjCC4PbYf9pGvO5VgRXiTfRjR6yac85ndV7SpYCDKCudf4wJ9M6tro=
  - secure: MPQZA8QcTJtJrLhHA7hGmrGE5Shr71gxOjjyVcX+KUHmLefWTX/wkz2AXntTq9sBHwBskKc0k7wqM/HRmC2JFgrhe+7zFqs6etILhISdZUizM3TKd7y2Dnm4U3KLBvtuoty3o9N2YsETmXhDsOZ4po8zyxLBuUmo2obIqk+TAyY=

cache:
  directories:
  - "$HOME/geosinstall"
  - "~/.cache/pip"

jobs:
  include:
  - arch: ppc64le
  - arch: s390x
  - arch: arm64
  - arch: arm64
    dist: bionic  # docker pull gives TLS handshake timeouts on focal
    services: docker
    env:
    - CIBUILDWHEEL=1
    - CIBW_BUILD="cp*-manylinux_aarch64"
    - CIBW_ENVIRONMENT_PASS_LINUX="GEOS_VERSION GEOS_INSTALL GEOS_CONFIG LD_LIBRARY_PATH"
    - CIBW_BEFORE_ALL="./ci/install_geos.sh"
    - CIBW_TEST_REQUIRES="pytest"
    - CIBW_TEST_COMMAND="pytest --pyargs shapely.tests"

install:
- |
  if [[ -z $CIBUILDWHEEL ]]; then
    export GEOS_INSTALL=$HOME/geosinstall/geos-$GEOS_VERSION
    ./ci/install_geos.sh
    export PATH=$HOME/geosinstall/geos-$GEOS_VERSION/bin:$PATH
    pip install .[test]
  else
    python3 -m pip install cibuildwheel==2.3.0
  fi

script:
- |
  if [[ -z $CIBUILDWHEEL ]]; then
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/geosinstall/geos-$GEOS_VERSION/lib
    cd ..
    pytest -v --pyargs shapely.tests
  else
    export GEOS_INSTALL=/host$HOME/geosinstall/geos-$GEOS_VERSION
    export GEOS_CONFIG=$GEOS_INSTALL/bin/geos-config
    export LD_LIBRARY_PATH=$GEOS_INSTALL/lib
    python3 -m cibuildwheel --output-dir dist
  fi

deploy:
  provider: pypi
  username: __token__
  password: $PYPI_TOKEN1$PYPI_TOKEN2$PYPI_TOKEN3
  skip_cleanup: true
  skip_existing: true
  on:
    tags: true
