[build-system]
requires = [
    "cython",
    "oldest-supported-numpy",
    "setuptools",
]
build-backend = "setuptools.build_meta"

# [project] -- see setup.cfg for project metadata

[tool.coverage.run]
source = ["shapely"]
omit = ["shapely/tests/*"]
