version: 2.1

jobs:
  linux-aarch64-wheels:
    working_directory: ~/linux-aarch64-wheels
    machine:
      image: ubuntu-2004:2022.04.1
    # resource_class is what tells CircleCI to use an ARM worker for native arm builds
    # https://circleci.com/product/features/resource-classes/
    resource_class: arm.medium
    environment:
      CIBUILDWHEEL: 1
      CIBW_BUILD: "cp*_aarch64"
      CIBW_MANYLINUX_AARCH64_IMAGE: ghcr.io/shapely/manylinux2014_aarch64_geos:3.11.4
      CIBW_MUSLLINUX_AARCH64_IMAGE: ghcr.io/shapely/musllinux_1_2_aarch64_geos:3.11.4
      CIBW_ENVIRONMENT: "PIP_PRE=1"
      CIBW_TEST_REQUIRES: "pytest"
      CIBW_TEST_COMMAND: "pytest --pyargs shapely.tests"
      CIBW_BUILD_VERBOSITY: 1
    steps:
      - checkout
      - run:
          name: Build the Linux aarch64 wheels.
          command: |
            python3 -m pip install --user cibuildwheel==2.19.2
            source "$BASH_ENV"
            python3 -m cibuildwheel --output-dir wheelhouse
      - store_artifacts:
          path: wheelhouse/

workflows:
  wheel-build:
    jobs:
      - linux-aarch64-wheels:
          filters:
            branches:
              only:
                - main
                - maint-2.0
            tags:
              only: /.*/
