name: shapely_docs
channels:
  - conda-forge
dependencies:
  - python=3.10
  - geos=3.11
  - numpy
  - cython=0.29
  - sphinx-book-theme
  - sphinx-remove-toctrees
  - numpydoc=1.1
  - matplotlib
  - pip
